ATPTopTen/Models/HeadToHead.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ATPTopTen.Models
{
    public class HeadToHead
    {
        [Key, Column(Order = 0)]
        public string WinnerId { get; set; }

        [Key, Column(Order = 1)]
        public string OpponentId { get; set; }

        public int? NumberOfWins { get; set; }
    }
}

ATPTopTen/Models/Player.cs
using System;
using System.Collections.Generic;

namespace ATPTopTen.Models
{
    public class Player
    {
        public string PlayerId { get; set; }

        public int Rank { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Obsolete]
        public string NatlCode { get; set; }

        public int? CountryId { get; set; }

        public int Points { get; set; }

        public bool IsTie { get; set; }

        public string CareerSummaryHtml { get; set; }

        public Country Country { get; set; }

        public IEnumerable<HeadToHead> HeadToHeads { get; set; }

        public bool IsFavorite { get; set; }
    }
}

ATPTopTen/Controllers/API/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using Newtonsoft.Json;
using ATPTopTen.DataTransferObjects;
using ATPTopTen.HelperClasses;
using ATPTopTen.Models;
using ATPTopTen.Properties;

namespace ATPTopTen.Controllers.API
{
    public class PlayersController : ApiController
    {
        private readonly ApplicationDbContext dbContext;

        public PlayersController()
        {
            //todo: dependency injection!!
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            //dispose dbcontext appropriately
            dbContext.Dispose();
        }

        /// <summary>
        /// GET ATP Top Ten players.
        /// </summary>
        /// <returns></returns>
        // GET /api/players
        [HttpGet]
        [ResponseType(typeof(IEnumerable<PlayerDto>))]
        public IHttpActionResult GetPlayers()
        {
            try
            {
                //get player data and eager load country too!!
                var players = dbContext.Players
                    .Include(x => x.Country).ToList();

                foreach (var player in players)
                {
                    //load head to heads
                    player.HeadToHeads =
                        dbContext.HeadToHead.Where(x => x.WinnerId == player.PlayerId).ToList();
                }

                //convert to dto and return
                return Ok(players.Select(Mapper.Map<Player, PlayerDto>));
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// Get ATP Top Ten Player by Player Id.
        /// Player Id is a string and it's the player's unique identifier.
        /// </summary>
        /// <param name="playerId"></param>
        /// <returns></returns>
        // GET /api/players/ABCD
        [HttpGet]
        [Route("api/players/{playerId}")]
        public IHttpActionResult GetPlayerByPlayerId(string playerId)
        {
            try
            {
                //get player data and eager load country too
                var player = dbContext.Players
                    .Include(x => x.Country)
                    .SingleOrDefault(x => x.PlayerId == playerId);

                //return if not found
                if (player == null)
                {
                    return NotFound();
                }

                //get head to head data
                player.HeadToHeads =
                    dbContext.HeadToHead.Where(x => x.WinnerId == player.PlayerId).ToList();

                //convert to dto and return
                return Ok(Mapper.Map<Player, PlayerDto>(player));
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// Get ATP Top Ten Player by Rank
        /// </summary>
        /// <param name="rank"></param>
        /// <returns></returns>
        // GET /api/players/1
        [HttpGet]
        [Route("api/players/rank/{rank}")]
        public IHttpActionResult GetPlayerByRank(int rank)
        {
            try
            {
                //get player data and country
                var player = dbContext.Players
                    .Include(x => x.Country)
                    .SingleOrDefault(x => x.Rank == rank);

                //return if not found
                if (player == null)
                {
                    return NotFound();
                }

                //get head to head data
                player.HeadToHeads =
                    dbContext.HeadToHead.Where(x => x.WinnerId == player.PlayerId).ToList();

                //convert to dto and return
                return Ok(Mapper.Map<Player, PlayerDto>(player));
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// Insert an ATP Top Ten player to the list.
        /// </summary>
        /// <param name="playerDto"></param>
        /// <returns></returns>
        //POST /api/players
        [HttpPost]
        public IHttpActionResult CreatePlayer(PlayerDto playerDto)
        {
            try
            {
                //return if not valid request
                if (!ModelState.IsValid)
                {
                    return BadRequest();
                }

                //return if player is null
                if (playerDto == null)
                {
                    return BadRequest("Required parameter Player is null");
                }

                //convert dto into player
                var player = Mapper.Map<PlayerDto, Player>(playerDto);

                //add to local db and save changes
                dbContext.Players.Add(player);
                dbContext.SaveChanges();

                //return created object
                return Created(new Uri(Request.RequestUri.ToString()), playerDto);
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// Update ATP Top Ten Player info.
        /// </summary>
        /// <param name="playerDto"></param>
        /// <param name="playerId"></param>
        /// <returns></returns>
        // PUT /api/players/ABCD
        [HttpPut]
        [Route("api/players/{playerId}")]
        public IHttpActionResult UpdatePlayer([FromBody]PlayerDto playerDto, string playerId)
        {
            try
            {
                //return if bad request
                if (!ModelState.IsValid)
                {
                    return BadRequest();
                }

                //return if player is null
                if (playerDto == null)
                {
                    return BadRequest("Required parameter Player is null");
                }

                //get player and country info
                var playerInDb = dbContext.Players.Include(x => x.Country)
                    .SingleOrDefault(x => x.PlayerId == playerId);

                //todo: create if not found?
                //return if no player found
                if (playerInDb == null)
                {
                    return NotFound();
                }

                //update all fields with automapper
                Mapper.Map(playerDto, playerInDb);

                //save to db
                dbContext.SaveChanges();

                //return updated dto
                return Ok(playerDto);
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// Delete ATP Top Ten player from the list
        /// </summary>
        /// <param name="playerId"></param>
        /// <returns></returns>
        //DELETE /api/players/ABCD
        [HttpDelete]
        [Route("api/players/{playerId}")]
        public IHttpActionResult DeletePlayer(string playerId)
        {
            try
            {
                //return if not valid state
                if (!ModelState.IsValid)
                {
                    return BadRequest();
                }

                //get player record in db
                var playerInDb = dbContext.Players.SingleOrDefault(x => x.PlayerId == playerId);

                //return if not found
                if (playerInDb == null)
                {
                    return NotFound();
                }

                //remove from db and save changes
                dbContext.Players.Remove(playerInDb);
                dbContext.SaveChanges();

                //return ok if no errors
                return Ok();
            }
            catch (Exception ex)
            {
                //return innermost exception if any
                return BadRequest(ExceptionHelper.FindInnermostException(ex).Message);
            }
        }

        /// <summary>
        /// get data needed for the Head to Head info
        /// </summary>
        /// <param name="player1Id"></param>
        /// <param name="player2Id"></param>
        /// <returns></returns>
        [Route("api/players/headtohead/{player1id}/{player2Id}")]
        public IHttpActionResult GetHeadToHeadData(string player1Id, string player2Id)
        {
            try
            {
                var winner = dbContext.Players.ToList().SingleOrDefault(x => x.PlayerId == player1Id);
                var opponent = dbContext.Players.ToList().SingleOrDefault(x => x.PlayerId == player2Id);

                //return if not found
                if (winner == null || opponent == null)
                {
                    //todo: make this check on the client side!!!
                    return NotFound();
                }

                if (winner == opponent)
                {
                    //todo: make this check on the client side!!!
                    return BadRequest();
                }

                //get head to head data
                winner.HeadToHeads = dbContext.HeadToHead.Where(x => x.WinnerId == winner.PlayerId).ToList();

ATPTopTen/Controllers/PlayerController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ATPTopTen.Models;
using ATPTopTen.ViewModel;
using Microsoft.Ajax.Utilities;

namespace ATPTopTen.Controllers
{
    public class PlayerController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public PlayerController()
        {
            //todo: dependency injection!! (unit testing)
            dbContext = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            //dispose of db context correctly
            dbContext.Dispose();
        }

        /// <summary>
        /// Get the ATP Top Ten players list, sorted by Rank.
        /// </summary>
        /// <param name="pageIndex"></param>
        /// <param name="sortBy"></param>
        /// <returns></returns>
        public ActionResult TopTenList(int? pageIndex, string sortBy, string player1Id, string player2Id)
        {
            //todo: add pagination
            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }

            //sort by Rank by default
            if (string.IsNullOrWhiteSpace(sortBy))
            {
                sortBy = "Rank";
            }

            //get players (include country too) and sort by Rank (default)
            var players = dbContext.Players.Include(x => x.Country).SortBy(sortBy);

            //initialize player 1 and 2
            var player1 = player1Id.IsNullOrWhiteSpace()
                //if null, get the first in the list
                ? players.FirstOrDefault()
                //if not null, get the first in the list that matches player 1 id
                : players.FirstOrDefault(x => x.PlayerId == player1Id);

            var player2 = player2Id.IsNullOrWhiteSpace()
                //if null, get the first in the list that is not player 1
                ? players.FirstOrDefault(x => x.PlayerId != player1.PlayerId)
                //if not null, get the first in the list that matches player 2 id
                : players.FirstOrDefault(x => x.PlayerId == player2Id);

            //create view model
            var playerListViewModel = new PlayerListViewModel()
            {
                Players = new List<Player>(),
                Head1Player = player1,
                Head2Player = player2
            };

            foreach (var player in players)
            {
                //eager loading head to heads
                player.HeadToHeads = dbContext.HeadToHead
                    .Where(x => x.WinnerId == player.PlayerId);

                //add to list
                playerListViewModel.Players.Add(player);
            }

            //return list of viewmodels
            return View(playerListViewModel);
        }

        /// <summary>
        /// Get player details of ATP Top Ten player by rank
        /// </summary>
        /// <param name="rank"></param>
        /// <returns></returns>
        //[Route("player/rank/{rank:regex(\\d{1,2}):range(1,10)}")]
        [Route("player/rank/{rank}")]
        public ActionResult PlayerDetailsByRank(int rank)
        {
            //get players list and country where rank = rank
            var players = dbContext.Players.Include(x => x.Country);
            var player = players.FirstOrDefault(x => x.Rank == rank);

            //return if not found
            if (player == null)
            {
                return HttpNotFound();
            }

            //eager loading head to heads
            player.HeadToHeads = dbContext.HeadToHead.Where(x => x.WinnerId == player.PlayerId);

            //create viewmodel
            var playerViewModel = new PlayerViewModel()
            {
                Players = players.ToList(),
                Player = player
            };

            //return viewmodel
            return View(playerViewModel);
        }

        /// <summary>
        /// Save Favorite setting, then reload the page
        /// </summary>
        /// <param name="rank"></param>
        /// <returns></returns>
        public ActionResult AddToFavorites(int rank)
        {
            //get players list and country where rank = rank
            var players = dbContext.Players.Include(x => x.Country);
            var player = players.FirstOrDefault(x => x.Rank == rank);

            //return if not found
            if (player == null)
            {
                return HttpNotFound();
            }

            //eager loading head to heads
            player.HeadToHeads = dbContext.HeadToHead.Where(x => x.WinnerId == player.PlayerId);

            //update favorite status
            player.IsFavorite = !player.IsFavorite;
            dbContext.SaveChanges();

            //create viewmodel
            var playerViewModel = new PlayerViewModel()
            {
                Players = players.ToList(),
                Player = player
            };

            //reload page
            //todo: call this with javascript!!
            return View("PlayerDetailsByRank", playerViewModel);
        }
    }
}

ATPTopTen/Views/Player/PlayerDetailsByRank.cshtml
@using Microsoft.Ajax.Utilities
@model ATPTopTen.ViewModel.PlayerViewModel

@functions {
    public string PlayerFullName { get; set; }
}

@{
    ViewBag.Title = "Player Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    PlayerFullName = Model.Player.FirstName + " " + Model.Player.LastName;
}
@{
    string positionClass;

    switch (Model.Player.Rank)
    {
        case 1:
            positionClass = "medium-size gold";
            break;
        case 2:
            positionClass = "medium-size silver";
            break;
        case 3:
            positionClass = "medium-size bronze";
            break;
        default:
            positionClass = null;
            break;
    }

    var favoritesButtonClass = Model.Player.IsFavorite ? "fav-star" : "fav-none";
    var favoritesImageClass = Model.Player.IsFavorite ? "fav-star-image" : string.Empty;
    var addToFavoritesButtonText = !Model.Player.IsFavorite
        ? "Add to Favorites"
        : "Remove Favorite ";

}
<br />
<div class="row">
    <div class="col-md-12">
        <div class="btn btn-primary">
            @{
                @Html.ActionLink("< Back to top ten", "TopTenList", "Player", null, null)
            }
        </div>
    </div>
</div>
<div id="details-container">
    <div class="row">
        <div class="col-md-6">
            <div class="inline">
                <h1>@PlayerFullName</h1>
            </div>
        </div>
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
            <button class="inline indented btn btn-primary fav-button">
                @{
                    @Html.ActionLink(addToFavoritesButtonText, "AddToFavorites", "Player", new { @rank = Model.Player.Rank }, new { @class = "fav fav-link " + favoritesButtonClass })
                }
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div id="header-details">
                <div class="inline">
                    <div class="detail-item">
                        <h3>
                            Ranking: @Model.Player.Rank <span class="@positionClass indented"></span>
                        </h3>
                    </div>
                    <div class="detail-item">
                        <h3>
                            Points: @Model.Player.Points
                        </h3>
                    </div>
                    <div class="detail-item">
                        <h3>
                            Nationality: @Model.Player.Country.Name <img class="inline black_border flag indented" src="~/Images/Countries/@(Model.Player.Country.Code).svg" alt="@Model.Player.Country.Name">
                        </h3>
                    </div>
                    <div class="detail-item">
                        <div class="inline">
                            <h3>
                                Favorite: @(Model.Player.IsFavorite ? "Yes" : "No")
                            </h3>
                        </div>
                        <div class="inline indented fav-small @favoritesImageClass"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-4 col-xs-2">
            @{
                var profileImagePath = "~/Images/Players/" + Model.Player.LastName + "1.jpg";
                if (File.Exists(Server.MapPath(profileImagePath)))
                {
                    <div id="profile-image" class="inline">
                        <img class="profilePicture" src="~/Images/Players/@(Model.Player.LastName)1.jpg" alt="@PlayerFullName" />
                    </div>
                }
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-8 col-xs-4">
            @{
                if (!Model.Player.CareerSummaryHtml.IsNullOrWhiteSpace())
                {
                    <div id="details-biography">
                        <h2 class="bold">Career Summary:</h2>
                        <p>
                            @(Html.Raw(HttpUtility.HtmlDecode(Model.Player.CareerSummaryHtml
                                  .Replace("<p>&gt; ", "<ul><li>").Replace("&gt;", "<li>"))))
                        </p>
                    </div>
                }
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-6 col-xs-4">
            @{
                var imagePath = "~/Images/Players/" + Model.Player.LastName + "2.jpg";
                if (File.Exists(Server.MapPath(imagePath)))
                {
                    <div id="details-picture">
                        <p>
                            <img class="fullPicture" src="~/Images/Players/@(Model.Player.LastName)2.jpg" alt="@PlayerFullName" />
                        </p>
                    </div>
                }
            }
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-4 col-xs-2">
        <div class="btn btn-primary">
            @{
                if (Model.Player.Rank > 1)
                {
                    @Html.ActionLink("< Previous", "PlayerDetailsByRank", "Player", new { rank = Model.Player.Rank - 1 }, null)
                }
                else
                {
                    @Html.ActionLink("< Back to top ten", "TopTenList", "Player", null, null)
                }
            }
        </div>
    </div>
    <div class="col-md-6 col-sm-4 col-xs-2">
        <div id="next-button" class="btn btn-primary">
            @{
                if (Model.Player.Rank < 10)
                {
                    @Html.ActionLink("Next >", "PlayerDetailsByRank", "Player", new { rank = Model.Player.Rank + 1 }, null)
                }
                else
                {
                    @Html.ActionLink("Go to Top Ten >", "TopTenList", "Player", null, null)
                }
            }
        </div>
    </div>
</div>

ATPTopTen/Views/Player/TopTenList.cshtml
@using ATPTopTen.Models
@model ATPTopTen.ViewModel.PlayerListViewModel

@functions {
    public List<Player> PlayerList { get; set; }
}

@{
    ViewBag.Title = "ATP Top Ten Players";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    PlayerList = Model.Players;

    var listItems = new List<SelectListItem>();

    foreach (var player in Model.Players)
    {
        var playerName = player.FirstName + " " + player.LastName;

        listItems.Add(new SelectListItem() { Text = playerName, Value = player.PlayerId });
    }
}

@*@Html.Partial("../Player/_HeadToHead")*@
<br />
<div class="row">
    <div class="container centered">
        <div class="col-md-12">
            <ul class="nav navbar-nav">
                <li class="indented" id="head1data">
                    @Html.DropDownListFor(x => x.Players, listItems, "-- Select Player --",
                        new
                        {
                            id = "Players-1",
                            onchange = "document.getElementById('Head1').value = this.value;"
                        })
                </li>
                <li class="indented"><span> Vs. </span></li>
                <li class="indented" id="head2data">
                    @Html.DropDownListFor(x => x.Players, listItems, "-- Select Player --",
                        new
                        {
                            id = "Players-2",
                            onchange = "document.getElementById('Head2').value = this.value;"
                        })
                </li>
            </ul>
            <p>@Html.Hidden("Head1")</p>
            <p>@Html.Hidden("Head2")</p>
            <div class="indented">
                <button id="head-button" class="indented btn btn-primary js-head">
                    Head to Head
                </button>
            </div>
            <div id="Head2HeadResults" class="centered bigTitle indented-top">
                @*Please pick two players...*@
                <ul class="nav navbar-nav">
                    <li class="indented">@(Model.Head1Player.FirstName) @(Model.Head1Player.LastName) (@(Model.Head1Player.HeadToHeads.FirstOrDefault(x => x.OpponentId == Model.Head2Player.PlayerId)?.NumberOfWins))</li>
                    <li class="indented"><span> Vs. </span></li>
                    <li class="indented">@(Model.Head2Player.FirstName) @(Model.Head2Player.LastName) (@(Model.Head2Player.HeadToHeads.FirstOrDefault(x => x.OpponentId == Model.Head1Player.PlayerId)?.NumberOfWins))</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <h1 class="indented40">@ViewBag.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div id="playerList" class="inline margin40">
            @foreach (var player in Model.Players)
            {
                string positionClass;

                switch (player.Rank)
                {
                    case 1:
                        positionClass = "small-size gold";
                        break;
                    case 2:
                        positionClass = "small-size silver";
                        break;
                    case 3:
                        positionClass = "small-size bronze";
                        break;
                    default:
                        positionClass = null;
                        break;
                }
                var playerName = @player.FirstName + " " + @player.LastName;

                var favoritesClass = player.IsFavorite ? "fav-star-image" : string.Empty;

                <div>
                    <h2 class="inline">
                        @player.Rank. @Html.ActionLink(playerName, "PlayerDetailsByRank", "Player", new { rank = player.Rank }, null)
                    </h2>
                    <div class="inline @positionClass"></div>
                    <div class="inline fav-small @favoritesClass"></div>
                </div>
            }
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <img max-height="500" height="500" src="~/Images/atp_masters_logo.png" />
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#head-button").on('click',
                function () {
                    //alert(document.getElementById('Head1').value);
                    var head1 = document.getElementById('Head1').value;
                    var head2 = document.getElementById('Head2').value;
                    $.ajax({
                        url: '../api/players/headtohead/' + head1 + '/' + head2,
                        method: 'GET',
                        success: function (result) {
                            //alert(result);
                            document.getElementById('Head2HeadResults').innerHTML = result;
                        }
                    });
                });
        });
    </script>
}

ATPTopTen/Views/Player/_HeadToHead.cshtml
@using ATPTopTen.Models
@model ATPTopTen.ViewModel.ViewModelBase

@functions {
    public List<Player> PlayerList { get; set; }
}

@{
    PlayerList = Model.Players;

    var listItems = new List<SelectListItem>();

    foreach (var player in Model.Players)
    {
        var playerName = player.FirstName + " " + player.LastName;

        listItems.Add(new SelectListItem() { Text = playerName, Value = player.PlayerId });
    }
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container margin20">
        <div id="centerednav" class="inline navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="head1data">@Html.DropDownListFor(x => x.Players, listItems, "-- Select Player --", new { id = "Players-1" })</li>
                <li><span>Vs.</span></li>
                <li id="head2data">@Html.DropDownListFor(x => x.Players, listItems, "-- Select Player --", new { id = "Players-2" })</li>
            </ul>
            <button class="btn btn-primary js-head">Go</button>
        </div>
        <div id="Head2HeadResults">
            Please pick two players...
        </div>
    </div>
</div>

@section scripts
{
    <script>
        //todo: this is not working...
        $(document).ready(function () {
            $('#centerednav .js-head').on('click',// '.js-head-button',
                function () {
                    var player1Id = $('#Players-1 option:selected').val();
                    var player2Id = $('#Players-2 option:selected').val();

                    var placeholder = document.getElementById("Head2HeadResults");
                    placeholder.innerHTML = player1Id + " Vs. " + player2Id;
                });
        });
    </script>
}